//
//  Copyright © 2026 - Jan-Hendrik Damerau. All rights reserved.
//

import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    // The name of the workspace
    name: Environment.appName,

    // The names of the projects that should be included in the workspace
    projects: [
        "App",
        "Modules/CoreDataKit",
        "Modules/PDFGenerator"
    ],

    // The schemes to be included in the workspace
    schemes: Schemes.makeAppSchemes(),

    // The file header template to be used for files generated in the workspace
    fileHeaderTemplate: .string("""
    //
    //  ___COPYRIGHT___
    //
    """),

    // Any additional files or folders to be added to the workspace
    additionalFiles: [
        "Dangerfile.swift", // A Dangerfile for automated code reviews
        .folderReference(path: "Scripts"), // A folder containing utility scripts
        "App/TestPlans/AllTests.xctestplan" // Shared test plan file
    ],

    // Generation options for the workspace
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false, // Disables automatic generation of Xcode schemes
        autogeneratedWorkspaceSchemes: .disabled // Disables the creation of workspace-level schemes
    )
)
